# Site settings
title: Belize
client:
  name: Belize
  link: "https://www.travelbelize.org/"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Discover an untamed paradise on the Caribbean. Belize is a tropical wonderland, a country that nurtures and protects its natural landscape leaving sprawling rainforests and miles of unspoilt, idyllic coastlines. 

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/belize" # the subpath of your site, e.g. /blog/
img:     "/belize/_assets/img"
css:     "/belize/_assets/css"
js:      "/belize/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed